modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/TwelveIterationMods/ForgivingVoid/issues"

[[mods]]
modId="forgivingvoid"
version="${file.jarVersion}"
displayName="Forgiving Void"
displayURL="https://blay09.net/mods/forgivingvoid"
logoFile="forgivingvoid-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Makes the void hate you a little less (and vice-versa). Fall down and come back out on top.
'''

[[dependencies.forgivingvoid]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.forgivingvoid]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.forgivingvoid]]
    modId="balm"
    mandatory=true
    versionRange="[5.0.0,)"
    ordering="NONE"
    side="BOTH"
