modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="All rights reserved"
issueTrackerURL="https://github.com/TwelveIterationMods/ForgivingVoid/issues"

[[mods]]
modId="forgivingvoid"
version="${file.jarVersion}"
displayName="Forgiving Void"
displayURL="https://mods.twelveiterations.com/mc/forgivingvoid"
logoFile="forgivingvoid-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Makes the void hate you a little less (and vice-versa). Fall down and come back out on top.
'''

[[dependencies.forgivingvoid]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.forgivingvoid]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.forgivingvoid]]
    modId="balm"
    mandatory=true
    versionRange="${balm_version_range}"
    ordering="NONE"
    side="BOTH"
